#!/usr/bin/env python3
"""Strict-ASCII manifest test (Section 9 of the archetype replacement plan).

Every fixed manifest member, every glob member, and every existing optional
generated artifact must decode as strict ASCII. A ``UnicodeDecodeError`` or a
byte above 0x7F fails the test with the offending path and character.
"""

from __future__ import annotations

import unittest
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent.parent

FIXED_MANIFEST = [
    "flake.nix",
    "core/archetype_catalog.py",
    "core/agent_plan_validator.py",
    "core/soul_creator.py",
    "core/translation_layer_creator.py",
    "core/alignment_spec.py",
    "core/health_check.py",
    "core/cli.py",
    "README.md",
    "AGENTS.md",
    "PRD.md",
    "profiles/alignment/domain_policy.json",
    "profiles/alignment/README.md",
    "docs/README.md",
    "docs/Agent-Archetype-System-Replacement-Implementation-Plan.md",
    "docs/Alignment-Artifacts-SOUL,-Archetype,-and-Alignment-Spec.md",
    "docs/Layer-Profiles.md",
    "docs/Alignment-Profile.md",
    "docs/CLI-and-Command-Reference.md",
    "docs/Workspaces-and-Generated-Artifacts.md",
    "tests/test_archetype_catalog.py",
    "tests/test_agent_plan_validator.py",
    "tests/test_soul_creator.py",
    "tests/test_translation_layer_creator.py",
    "tests/test_alignment_spec.py",
    "tests/test_health.py",
    "tests/test_ascii.py",
]

# Generated by the pipeline; included only when present.
OPTIONAL_MANIFEST = [
    "workspaces/alignment/artifacts/agent_plan.json",
    "workspaces/alignment/artifacts/INTERACTION_POSTURE.md",
    "workspaces/alignment/artifacts/persona_map.md",
]

GLOBS = [
    "profiles/alignment/archetypes/*.json",
    "profiles/alignment/prompts/*.md",
    "workspaces/alignment/artifacts/agents/*.md",
]


def manifest_paths() -> List[Path]:
    """Expand the fixed manifest, globs, and existing optional paths."""
    paths = {ROOT / relative for relative in FIXED_MANIFEST}
    paths.update(
        ROOT / relative for relative in OPTIONAL_MANIFEST if (ROOT / relative).exists()
    )
    for pattern in GLOBS:
        paths.update(ROOT.glob(pattern))
    return sorted(paths)


class AsciiManifestTests(unittest.TestCase):
    def test_every_fixed_manifest_member_exists(self) -> None:
        missing = [
            relative for relative in FIXED_MANIFEST if not (ROOT / relative).exists()
        ]
        self.assertEqual(missing, [])

    def test_globs_are_non_empty(self) -> None:
        for pattern in GLOBS[:2]:  # agents/ is empty before the first build
            with self.subTest(pattern=pattern):
                self.assertTrue(list(ROOT.glob(pattern)))

    def test_manifest_is_strict_ascii(self) -> None:
        for path in manifest_paths():
            with self.subTest(path=str(path.relative_to(ROOT))):
                raw = path.read_bytes()
                try:
                    text = raw.decode("ascii")
                except UnicodeDecodeError as exc:
                    offending = raw[exc.start:exc.end]
                    self.fail(
                        f"{path.relative_to(ROOT)} is not ASCII at byte "
                        f"{exc.start}: {offending!r}"
                    )
                self.assertTrue(text.isascii())

    def test_no_legacy_posture_or_archetype_paths_remain(self) -> None:
        for legacy in (
            "profiles/alignment/prompts/soul_archetype_seed.md",
            "workspaces/alignment/artifacts/SOUL_ARCHETYPE.md",
            "profiles/alignment/archetypes/pattern-scout.json",
            "profiles/alignment/archetypes/constraint-reader.json",
            "profiles/alignment/archetypes/commitment-anchor.json",
        ):
            with self.subTest(path=legacy):
                self.assertFalse((ROOT / legacy).exists())


if __name__ == "__main__":
    unittest.main()
